# Generated by Django 4.1.5 on 2023-01-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_person_age_person_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='accDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='anon', max_length=20),
        ),
    ]
