# Generated by Django 4.1.5 on 2023-01-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_person_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(default='none', max_length=20)),
                ('acres', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.TextField(default='empty')),
            ],
        ),
        migrations.RenameField(
            model_name='person',
            old_name='accDate',
            new_name='acc_date',
        ),
    ]
