# Generated by Django 4.1.5 on 2023-01-26 18:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_house_rename_accdate_person_acc_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='acc_date',
        ),
        migrations.AddField(
            model_name='house',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.person'),
            preserve_default=False,
        ),
    ]
