# Generated by Django 4.1.5 on 2023-01-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_house_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='owner',
        ),
    ]
