# Generated by Django 4.1.5 on 2023-01-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_house_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='wealth',
            field=models.IntegerField(default=0),
        ),
    ]
