# Generated by Django 4.1.5 on 2023-02-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_person_ethnicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.BooleanField(default=True),
        ),
    ]
