# Generated by Django 4.1.5 on 2023-02-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_person_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='forsale',
            field=models.BooleanField(default=True),
        ),
    ]
