# Generated by Django 4.1.5 on 2023-02-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_house_forsale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='anon', max_length=20)),
                ('content', models.TextField(verbose_name='blank')),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
