# Generated by Django 4.1.5 on 2023-02-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_room_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.CharField(default='Anon', max_length=20),
        ),
    ]
